### PR TITLE
Fix adding CanvasPattern

### PR DESCRIPTION
**Pull request by x4d3**
The current code was going into an infinite loop.
It's also setting `patternUnits` to `userSpaceOnUse` in order to get the same behaviour as canvas patterns

### CODE REVIEW

**Comment by x4d3** [comment]
Dear @zenozeng

I took the liberty of writing this PR to fix an infinite loop when `createPattern` was called.

Please have a look.

Thanks

**Comment by zenozeng** [comment]
@x4d3 
Thanks for your pull request. Your code looks good to me. 👍
There is only one small question, what is the copyright agreement of the `pattern.png`? Is it licensed under Creative Commons (CC) license?

**Comment by x4d3** [comment]
@zenozeng Good question,

I took the image from here: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/createPattern

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/createPattern/canvas_createpattern.png

so I assumed it was free to use.

To be fair any image would do.

**Comment by zenozeng** [comment]
@x4d3 Thanks!

**Pull request merged**
